In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.8.0+cu126


# Creating Tensors

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# know the dimension of the tensor
scalar.ndim

0

In [6]:
# get tensor back as a python int
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([1,2,3,45])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([4])

In [10]:
#   MATRIX
MATRIX = torch.tensor([[11,22],
                       [33,44]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([33, 44])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,1,1],
                        [2,2,2],
                        [3,3,3]]])

TENSOR

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [18]:
TENSOR[0,1]

tensor([2, 2, 2])

In [19]:
TENSOR[0,0]

tensor([1, 1, 1])

In [20]:
TENSOR[0,2]

tensor([3, 3, 3])

In [21]:
TENSOR[0,2,2]

tensor(3)

### Random Tensors

In [22]:
# create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0950, 0.1004, 0.6432, 0.5569],
        [0.7945, 0.1476, 0.5908, 0.8108],
        [0.1042, 0.5327, 0.0236, 0.5416]])

In [23]:
random_tensor.ndim

2

In [24]:
tensor1 = torch.rand((1,10,10))
tensor1

tensor([[[5.9035e-02, 9.7009e-01, 1.1264e-01, 1.8958e-01, 4.9042e-01,
          2.6223e-01, 4.7956e-01, 1.5895e-01, 2.9079e-01, 5.6734e-01],
         [9.0894e-01, 5.3681e-01, 5.2837e-02, 7.6790e-01, 9.7768e-01,
          4.3837e-01, 8.0054e-01, 8.8541e-01, 8.4424e-02, 1.4968e-01],
         [8.0779e-01, 2.7226e-01, 4.2763e-01, 7.7952e-01, 5.9249e-01,
          5.1600e-01, 9.9700e-01, 9.1168e-01, 8.3488e-01, 8.9625e-01],
         [9.4319e-01, 2.5640e-01, 1.7482e-01, 8.4408e-01, 6.1430e-01,
          1.3567e-01, 7.6670e-02, 1.3025e-01, 5.8076e-01, 7.4940e-01],
         [6.0942e-01, 1.0676e-01, 3.4653e-01, 5.3222e-01, 5.1460e-01,
          9.9203e-01, 3.8787e-01, 1.5783e-01, 7.6761e-01, 8.7981e-01],
         [4.0704e-01, 8.9373e-01, 1.3796e-01, 6.2478e-01, 7.2279e-01,
          2.3997e-01, 1.7596e-01, 6.2587e-02, 5.8190e-02, 2.2348e-01],
         [7.9396e-01, 5.7051e-01, 7.1417e-01, 7.7104e-01, 3.5891e-01,
          8.7392e-02, 9.3723e-01, 3.3339e-01, 9.8175e-01, 8.5639e-01],
         [6.1

In [25]:
tensor1.ndim

3

In [26]:
random_tensor

tensor([[0.0950, 0.1004, 0.6432, 0.5569],
        [0.7945, 0.1476, 0.5908, 0.8108],
        [0.1042, 0.5327, 0.0236, 0.5416]])

In [27]:
# random tensor with image shape
random_image_size_tensor = torch.rand(224,224,3)
random_image_size_tensor

tensor([[[0.0109, 0.1914, 0.2508],
         [0.0087, 0.1291, 0.2467],
         [0.4241, 0.8860, 0.0254],
         ...,
         [0.2824, 0.7661, 0.3434],
         [0.5381, 0.2234, 0.5451],
         [0.7200, 0.4971, 0.4069]],

        [[0.3173, 0.5350, 0.4504],
         [0.5424, 0.7026, 0.3982],
         [0.4453, 0.2410, 0.9845],
         ...,
         [0.0184, 0.3329, 0.1528],
         [0.4612, 0.7162, 0.5647],
         [0.1837, 0.7123, 0.2742]],

        [[0.7072, 0.8146, 0.2011],
         [0.6832, 0.6587, 0.0587],
         [0.9489, 0.5099, 0.7011],
         ...,
         [0.5984, 0.2670, 0.1834],
         [0.5891, 0.7875, 0.3252],
         [0.2596, 0.3734, 0.9812]],

        ...,

        [[0.2771, 0.4692, 0.7604],
         [0.1825, 0.1068, 0.5527],
         [0.8574, 0.3227, 0.7182],
         ...,
         [0.1554, 0.7374, 0.8541],
         [0.6371, 0.3714, 0.4574],
         [0.8968, 0.0617, 0.4036]],

        [[0.5482, 0.4027, 0.4142],
         [0.5656, 0.7465, 0.5022],
         [0.

In [28]:
random_image_size_tensor.ndim

3

In [29]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [30]:
torch.rand(3,3)

tensor([[0.2537, 0.4337, 0.3284],
        [0.3142, 0.0436, 0.9718],
        [0.3594, 0.1874, 0.7724]])

In [31]:
# Zeros tensor

zeros_tensor = torch.zeros(3,4)
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
# Ones tensor

ones_tensor = torch.ones(3,4)
ones_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones_tensor.dtype

torch.float32

In [34]:
zeros = torch.zeros(100,100)
zeros

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [35]:
ones = torch.ones(100,100)
ones

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

## Arange tensors and tensors like

In [36]:
# using arange function

one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arange_tensor = torch.arange(start = 1, end = 1000, step = 45)
arange_tensor

tensor([  1,  46,  91, 136, 181, 226, 271, 316, 361, 406, 451, 496, 541, 586,
        631, 676, 721, 766, 811, 856, 901, 946, 991])

In [38]:
torch.__version__

'2.8.0+cu126'

In [39]:
# creating tensors like
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor Datatypes

In [42]:
float_32 = torch.tensor([1,2,3,4,5.32])
float_32

tensor([1.0000, 2.0000, 3.0000, 4.0000, 5.3200])

In [43]:
float_32.dtype

torch.float32

In [44]:
float_16 = torch.tensor([1,2,4,5,6], dtype = torch.float16)
float_16

tensor([1., 2., 4., 5., 6.], dtype=torch.float16)

In [45]:
float_64 = torch.tensor([11,22,33,44,55], dtype = torch.float64)
float_64

tensor([11., 22., 33., 44., 55.], dtype=torch.float64)

# Tensor Attributes

In [46]:
some_tensor = torch.rand(3,3)

In [47]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8918, 0.3399, 0.5284],
        [0.6958, 0.1314, 0.4136],
        [0.4406, 0.3735, 0.3204]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 3])
Device tensor is on: cpu


# Tensors Operations

In [48]:
# create a tensor

tensor = torch.tensor([12,334,54])
tensor

tensor([ 12, 334,  54])

In [49]:
# multiply tensor
tensor * 122

tensor([ 1464, 40748,  6588])

In [50]:
# adding tensor
tensor + 190

tensor([202, 524, 244])

In [51]:
# subtracting tensor
tensor - 100

tensor([-88, 234, -46])

In [52]:
# multiply tensor
torch.mul(tensor, 10)

tensor([ 120, 3340,  540])

In [53]:
# addition of tensor
torch.add(tensor, 212)

tensor([224, 546, 266])

In [54]:
tensor1 = torch.rand((2,3))
tensor2 = torch.rand((3,2))
print(tensor1)
print(tensor2)

tensor([[0.3525, 0.6666, 0.9657],
        [0.8707, 0.2224, 0.5524]])
tensor([[0.2810, 0.3537],
        [0.1978, 0.9150],
        [0.0524, 0.4283]])


In [55]:
torch.matmul(tensor1, tensor2)

tensor([[0.2815, 1.1482],
        [0.3176, 0.7481]])

In [56]:
tensor2 = torch.rand((3,2))
tensor1 = torch.rand((2,3))
print(tensor1)
print(tensor2)

tensor([[0.7486, 0.7122, 0.9593],
        [0.5497, 0.9630, 0.1311]])
tensor([[0.6016, 0.6983],
        [0.5695, 0.5205],
        [0.4786, 0.4456]])


In [57]:
torch.matmul(tensor2, tensor1)

tensor([[0.8341, 1.1009, 0.6686],
        [0.7124, 0.9069, 0.6145],
        [0.6031, 0.7699, 0.5175]])

# Tensors Aggregation

In [58]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [59]:
torch.max(x)

tensor(90)

In [60]:
torch.min(x)

tensor(0)

In [61]:
torch.mean(x, dtype=torch.float16)

tensor(45., dtype=torch.float16)

In [62]:
torch.sum(x)

tensor(450)

# Finding positional min and **max**

In [63]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
torch.argmin(x)

tensor(0)

In [65]:
torch.argmax(x)

tensor(9)

# Reshaping, Stacking, Squeezing and Unsqueezing Tensors

In [66]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
x_reshaped = x.reshape(1,3,3)
x_reshaped

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [69]:
x_reshaped2 = x.reshape(9,1)
x_reshaped2

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [71]:
# stack
x_stacked = torch.stack([x,x,x,x,x,x,x,x,x])
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [76]:
# torch squeeze
x_squeezed = torch.arange(1,9)
x_squeezed = x_squeezed.reshape(1,8)
x_squeezed.shape

torch.Size([1, 8])

In [77]:
x_squeezed

tensor([[1, 2, 3, 4, 5, 6, 7, 8]])

In [78]:
x_squeezed.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
# torch unsqueezed
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed

tensor([[[1, 2, 3, 4, 5, 6, 7, 8]]])

# Indexing in Torch

In [82]:
y = torch.arange(1,10).reshape(1,3,3)
y, y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [83]:
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [84]:
y[0][0]

tensor([1, 2, 3])

In [85]:
y[0][1]

tensor([4, 5, 6])

In [86]:
y[0][2]

tensor([7, 8, 9])

In [88]:
y[0][0][0]

tensor(1)

In [89]:
y[0][2][2]

tensor(9)

In [90]:
y[:,0]

tensor([[1, 2, 3]])

In [91]:
y[:,:,1]

tensor([[2, 5, 8]])

In [92]:
y[:,:,2]

tensor([[3, 6, 9]])

# Pytorch tensors and numpy

In [95]:
array = np.array([1,23,4,56,7,9,564,453,1])
array

array([  1,  23,   4,  56,   7,   9, 564, 453,   1])

In [96]:
tensor = torch.from_numpy(array)
tensor

tensor([  1,  23,   4,  56,   7,   9, 564, 453,   1])