In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
else:
  print("GPU is not available")

GPU is not available


# Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.zeros(1,2,3,4)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [ ]:
# using ones
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.ones(2,4,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.9662, 0.5248, 0.9768],
        [0.1406, 0.0080, 0.3564]])

In [ ]:
torch.rand(3,3,3)

tensor([[[0.4888, 0.8586, 0.9910],
         [0.2366, 0.4152, 0.2925],
         [0.5912, 0.9945, 0.9716]],

        [[0.3946, 0.0377, 0.7208],
         [0.4694, 0.6238, 0.2617],
         [0.6676, 0.8587, 0.8085]],

        [[0.6856, 0.2234, 0.5620],
         [0.3235, 0.0489, 0.6381],
         [0.1874, 0.2771, 0.3652]]])

In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(4,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183, 0.9014]])

# Other ways

In [ ]:
# arange
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# linspace
torch.linspace(1,10,10)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# using eye
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# using full
torch.full((5,5),10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

In [ ]:
torch.full((2,2),100)

tensor([[100, 100],
        [100, 100]])

# Tensor Shape

In [ ]:
x = torch.tensor([[1,1,1],[2,2,2],[3,3,3]])
x

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [ ]:
x.shape

torch.Size([3, 3])

In [ ]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.9751, 0.7911, 0.4274],
        [0.4460, 0.5522, 0.9559],
        [0.9405, 0.2215, 0.3271]], dtype=torch.float64)

# Tensor Data Types

In [ ]:
# find the data type
x.dtype

torch.int64

In [ ]:
torch.tensor([1,2,3,4,5,6], dtype=torch.int64)

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
torch.tensor([11,22,33,44,55], dtype=torch.float32)

tensor([11., 22., 33., 44., 55.])

In [ ]:
x

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [ ]:
x.dtype

torch.int64

In [ ]:
x.to(torch.float32)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [ ]:
x.to(torch.float64)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

1. Scalar Operation

In [ ]:
A = torch.rand(4,4)
A

tensor([[0.0169, 0.2209, 0.9535, 0.7064],
        [0.1629, 0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182, 0.5261],
        [0.0447, 0.5123, 0.9051, 0.5989]])

In [ ]:
# Substraction
A - .9000

tensor([[-0.8831, -0.6791,  0.0535, -0.1936],
        [-0.7371, -0.0098, -0.3837, -0.8641],
        [-0.2524, -0.5570, -0.5818, -0.3739],
        [-0.8553, -0.3877,  0.0051, -0.3011]])

In [ ]:
# Addition
A + 1.000

tensor([[1.0169, 1.2209, 1.9535, 1.7064],
        [1.1629, 1.8902, 1.5163, 1.0359],
        [1.6476, 1.3430, 1.3182, 1.5261],
        [1.0447, 1.5123, 1.9051, 1.5989]])

In [ ]:
# multiplication
A * 0.00

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# division
A / 0.5

tensor([[0.0338, 0.4418, 1.9071, 1.4128],
        [0.3258, 1.7804, 1.0325, 0.0718],
        [1.2953, 0.6861, 0.6365, 1.0522],
        [0.0893, 1.0247, 1.8102, 1.1977]])

In [ ]:
# int division
(A * 100)//5

tensor([[ 0.,  4., 19., 14.],
        [ 3., 17., 10.,  0.],
        [12.,  6.,  6., 10.],
        [ 0., 10., 18., 11.]])

In [ ]:
# mod
((A * 100)//2)%2

tensor([[0., 1., 1., 1.],
        [0., 0., 1., 1.],
        [0., 1., 1., 0.],
        [0., 1., 1., 1.]])

In [ ]:
# power
A**0.05

tensor([[0.8154, 0.9273, 0.9976, 0.9828],
        [0.9133, 0.9942, 0.9675, 0.8467],
        [0.9785, 0.9479, 0.9444, 0.9684],
        [0.8560, 0.9671, 0.9950, 0.9747]])

2. Element wise operations

In [ ]:
a = torch.rand(2,4)
b = torch.rand(2,4)
print(a)
print(b)

tensor([[0.4450, 0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896, 0.3687]])
tensor([[0.9053, 0.8356, 0.3039, 0.6726],
        [0.5740, 0.9233, 0.9178, 0.7590]])


In [ ]:
# add
a+b

tensor([[1.3503, 1.5634, 0.7602, 1.0115],
        [1.1951, 1.4763, 1.6074, 1.1278]])

In [ ]:
# subtract
a-b

tensor([[-0.4603, -0.1077,  0.1524, -0.3338],
        [ 0.0472, -0.3703, -0.2282, -0.3903]])

In [ ]:
# multiply
a*b

tensor([[0.4028, 0.6082, 0.1387, 0.2279],
        [0.3565, 0.5106, 0.6329, 0.2799]])

In [ ]:
# division
a/b

tensor([[0.4916, 0.8711, 1.5013, 0.5038],
        [1.0822, 0.5990, 0.7514, 0.4858]])

In [ ]:
# int division
a//b

tensor([[0., 0., 1., 0.],
        [1., 0., 0., 0.]])

In [ ]:
# power
a**b

tensor([[0.4805, 0.7669, 0.7878, 0.4829],
        [0.7609, 0.5787, 0.7110, 0.4689]])

In [ ]:
# mod
a%b

tensor([[0.4450, 0.7278, 0.1524, 0.3389],
        [0.0472, 0.5530, 0.6896, 0.3687]])

In [ ]:
c = torch.tensor([11,22,33,44,55], dtype=torch.float32)

In [ ]:
# absolute
torch.abs(c)

tensor([11., 22., 33., 44., 55.])

In [ ]:
# negative
torch.neg(c)

tensor([-11., -22., -33., -44., -55.])

In [ ]:
d = torch.tensor([1.1,2.2,3.3,4.4,5.5])
d

tensor([1.1000, 2.2000, 3.3000, 4.4000, 5.5000])

In [ ]:
# round
torch.round(d)

tensor([1., 2., 3., 4., 6.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5., 6.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4., 5.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.2000, 3.3000, 4.0000, 4.0000])

3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low = 0, high=10, dtype=torch.float32)
e

tensor([[8., 3., 3.],
        [5., 0., 6.]])

In [ ]:
# sum
torch.sum(e)

tensor(25.)

In [ ]:
# sum along columns
torch.sum(e, dim=0)

tensor([13.,  3.,  9.])

In [ ]:
# mean
torch.mean(e)

tensor(4.1667)

In [ ]:
# median
torch.median(e)

tensor(3.)

In [ ]:
# max
torch.max(e)

tensor(8.)

In [ ]:
# min
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.7869)

In [ ]:
# variance
torch.var(e)

tensor(7.7667)

In [ ]:
# argmax
torch.argmax(e)

tensor(0)

In [ ]:
# argmin
torch.argmin(e)

tensor(4)

4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
g = torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)
print(f)
print(g)

tensor([[5., 0., 4.],
        [2., 7., 1.]])
tensor([[1., 5.],
        [4., 4.],
        [1., 1.]])


In [ ]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 9., 29.],
        [31., 39.]])

In [ ]:
vector1 = torch.tensor([1,2,4,5,6])
vector2 = torch.tensor([7,8,9,11,12])

In [ ]:
# dot product
torch.dot(vector1, vector2)

tensor(186)

In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[5., 2.],
        [0., 7.],
        [4., 1.]])

In [ ]:
h = torch.randint(size=(3,3), low = 0, high = 10,   dtype=torch.float32)
h

tensor([[1., 4., 5.],
        [6., 9., 2.],
        [3., 1., 0.]])

In [ ]:
# determinant
torch.det(h)

tensor(-83.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[ 0.0241, -0.0602,  0.4458],
        [-0.0723,  0.1807, -0.3373],
        [ 0.2530, -0.1325,  0.1807]])

5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float32)
j = torch.randint(size=(2,3), low = 0, high = 10, dtype = torch.float32)
print(i)
print(j)

tensor([[2., 1., 2.],
        [7., 9., 2.]])
tensor([[4., 6., 6.],
        [8., 4., 9.]])


In [ ]:
# greater than
i > j

tensor([[False, False, False],
        [False,  True, False]])

In [ ]:
# less than
i < j

tensor([[ True,  True,  True],
        [ True, False,  True]])

In [ ]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])